export const MEMBERSHIP_PLANS = [
  {
    planId: 1,
    planName: "S",
    price: "₹4000",
    description: "Basic plan with limited access.",
    activities: ["Get access to 2500+ partner venues in 6 European countries"],
    live: ["Online Classes: Up to 4 check-ins"],
    video: ["Video on Demand"],
  },
  {
    planId: 2,
    planName: "M",
    price: "₹6000",
    description: "Standard plan with more features.",
    activities: ["Get access to 2500+ partner venues in 6 European countries"],
    live: ["Online Classes: Up to 8 check-ins"],
    video: ["Video on Demand with exclusive content"],
  },
  {
    planId: 3,
    planName: "L",
    price: "₹8000",
    description: "Extended plan with additional benefits.",
    activities: ["Get access to 3500+ partner venues in 8 European countries"],
    live: ["Online Classes: Up to 12 check-ins"],
    video: ["Video on Demand with premium content"],
  },
  {
    planId: 4,
    planName: "XL",
    price: "₹10000",
    description: "All-inclusive plan with maximum benefits.",
    activities: ["Get access to 4500+ partner venues in 10 European countries"],
    live: ["Online Classes: Unlimited check-ins"],
    video: ["Video on Demand with all-access content"],
  },
];
